#!/usr/bin/env ruby
#
#             __         ____
#       _____/ /_  ___  / / /___ _____  ____
#      / ___/ __ \/ _ \/ / / __ `/ __ \/ __ \
#     (__  ) / / /  __/ / / /_/ / /_/ / /_/ /
#    /____/_/ /_/\___/_/_/\__,_/ .___/ .___/
#                             /_/   /_/
#
# shellapp
#
# Turn a shell script into an OS X application.
#
# Usage:
#
#   shellapp example.sh example.app

require 'tempfile'

source = ARGV[0]
target = ARGV[1]

if ARGV[0] == "-h" || !ARGV[0] || !ARGV[1]
  puts  "Description: Turn a shell script into an OS X application.\n" +
        "Usage: shellapp source destination.app"
elsif target !~ /.app$/
  puts "Error: Target must have a .app extension."
elsif File.exists?(target)
  puts "Error: File already exists at target location."
else
  if File.exists?(source)
    input = File.open(source).read
  else
    input = source
  end

  applescript = %Q|#!/usr/bin/osascript\n| +
                %Q|do shell script "#{input}"|


  t = Tempfile.new('applescript', '/tmp').tap do |file|
    file.write(applescript)
  end
  t.rewind

  %x[osacompile -o #{target} #{t.path}]
end
